make rebase durable to failing again after rebase
also fix pipefail masking the error

Signed-off-by: Chris Brown <cbrown@pivotal.io>

diff --git a/assets/out b/assets/out
--- a/assets/out
+++ b/assets/out
@@ -51,14 +51,24 @@ git remote add push-target $uri
 
 if [ "$rebase" = "true" ]; then
   while true; do
+    echo "rebasing..."
+
     git pull --rebase push-target $branch
 
-    if git push --tags push-target HEAD:refs/heads/$branch 2>&1 | tee /tmp/push-failure; then
+    result=0
+
+    {
+      git push --tags push-target HEAD:refs/heads/$branch 2>&1 || result=$?
+    } | tee /tmp/push-failure
+
+    if [ "$result" = "0" ]; then
+      echo "pushed"
       break
     fi
 
-    # failed for reason other than non-fast-forward
-    if ! grep non-fast-forward /tmp/push-failure 2>/dev/null; then
+    # failed for reason other than non-fast-forward / fetch-first
+    if ! grep -q '\[rejected\]' /tmp/push-failure; then
+      echo "failed with non-rebase error"
       exit 1
     fi
 
